/**
 * Jalisco School Finder - Mock Data
 * This file represents the data typically received from a REST API.
 */

const niveles = {
  total: 10,
  data: [
    "BACHILLERATO",
    "CAM",
    "FORMACIÓN PARA EL TRABAJO",
    "INICIAL",
    "INICIAL GENERAL",
    "LICENCIATURA",
    "PREESCOLAR",
    "PRIMARIA",
    "RECTORÍA",
    "SECUNDARIA"
  ]
};

const municipios = {
  total: 7,
  data: [
    "ACATIC",
    "ACATLÁN DE JUÁREZ",
    "AHUALULCO DE MERCADO",
    "AMACUECA",
    "AMATITÁN",
    "AMECA",
    "ARANDAS"
  ]
};

const escuelas = {
  total: 15,
  page: 1,
  limit: 50,
  totalPages: 1,
  data: [
    {
      nombre: "GASTON GARCIA CANTU",
      clave: "14DJN2316V",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "ACATIC",
      localidad: "LOS OCOTES",
      tipoedu: "BÁSICA",
      nivel: "PREESCOLAR",
      subNivel: "GENERAL",
      control: "PÚBLICO",
      subControl: "FEDERAL TRANSFERIDO",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "C.E.C.A.D.E.E. BENITO JUAREZ",
      clave: "14DML0083H",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "ACATIC",
      localidad: "ZAPOPAN",
      tipoedu: "ESPECIAL",
      nivel: "CAM",
      subNivel: "U.S.A.E.R.",
      control: "PÚBLICO",
      subControl: "FEDERAL TRANSFERIDO",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "ADOLFO SANCHEZ VAZQUEZ",
      clave: "14EES0082S",
      turno: "VESPERTINO",
      entidad: "JALISCO",
      municipio: "ACATLÁN DE JUÁREZ",
      localidad: "HACIENDA LOS FRESNOS",
      tipoedu: "BÁSICA",
      nivel: "SECUNDARIA",
      subNivel: "GENERAL",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "2",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "ADOLFO SANCHEZ VAZQUEZ",
      clave: "14EES0082S",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "ACATLÁN DE JUÁREZ",
      localidad: "HACIENDA LOS FRESNOS",
      tipoedu: "BÁSICA",
      nivel: "SECUNDARIA",
      subNivel: "GENERAL",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "MARIA IZQUIERDO",
      clave: "14EJN1100O",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "AHUALULCO DE MERCADO",
      localidad: "SANTA CRUZ DEL VALLE",
      tipoedu: "BÁSICA",
      nivel: "PREESCOLAR",
      subNivel: "GENERAL",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "MIGUEL AGUSTIN ROMERO MORETT",
      clave: "14EJN1101N",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "AHUALULCO DE MERCADO",
      localidad: "HACIENDA SANTA FE",
      tipoedu: "BÁSICA",
      nivel: "PREESCOLAR",
      subNivel: "GENERAL",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "ESCUELA BANCARIA Y COMERCIAL, CAMPUS GUADALAJARA",
      clave: "14MSU0302N",
      turno: "DISCONTINUO",
      entidad: "JALISCO",
      municipio: "AHUALULCO DE MERCADO",
      localidad: "ZAPOPAN",
      nivel: "RECTORÍA",
      control: "PRIVADO",
      subControl: "PRIVADO",
      idTurno: "4",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "CENTRO EDUCATIVO ABC DE GUADALAJARA",
      clave: "14PJN1619N",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "AMACUECA",
      localidad: "GUADALAJARA",
      tipoedu: "BÁSICA",
      nivel: "PREESCOLAR",
      subNivel: "GENERAL",
      control: "PRIVADO",
      subControl: "PRIVADO",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "ESCUELA BANCARIA Y COMERCIAL, CAMPUS GUADALAJARA",
      clave: "14PSU0363Y",
      turno: "DISCONTINUO",
      entidad: "JALISCO",
      municipio: "AMACUECA",
      localidad: "ZAPOPAN",
      tipoedu: "SUPERIOR",
      nivel: "LICENCIATURA",
      subNivel: "LICENCIATURA UNIVERSITARIA Y TECNOLÓGICA",
      control: "PRIVADO",
      subControl: "PRIVADO",
      idTurno: "4",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "CECYTEJ PLANTEL ZAPOPAN SANTA MARGARITA (EXTENSION VALENTIN GOMEZ FARIAS)",
      clave: "14XTC0001X",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "AMACUECA",
      localidad: "ZAPOPAN",
      tipoedu: "MEDIA SUPERIOR",
      nivel: "BACHILLERATO",
      subNivel: "TECNOLÓGICO",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "CECYTEJ PLANTEL ZAPOPAN SANTA MARGARITA (EXTENSION VALENTIN GOMEZ FARIAS)",
      clave: "14XTC0001X",
      turno: "VESPERTINO",
      entidad: "JALISCO",
      municipio: "AMATITÁN",
      localidad: "ZAPOPAN",
      tipoedu: "MEDIA SUPERIOR",
      nivel: "BACHILLERATO",
      subNivel: "TECNOLÓGICO",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "2",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "CECYTEJ PLANTEL EL SALTO (EXTENSION LA HIGUERA)",
      clave: "14XTC0002W",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "AMATITÁN",
      localidad: "SAN JOSÉ EL VERDE (EL VERDE)",
      tipoedu: "MEDIA SUPERIOR",
      nivel: "BACHILLERATO",
      subNivel: "TECNOLÓGICO",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "CECYTEJ PLANTEL TONALA EL PANORAMICO (EXTENSION TOLOLOTLAN)",
      clave: "14XTC0003V",
      turno: "VESPERTINO",
      entidad: "JALISCO",
      municipio: "AMECA",
      localidad: "PUENTE GRANDE",
      tipoedu: "MEDIA SUPERIOR",
      nivel: "BACHILLERATO",
      subNivel: "TECNOLÓGICO",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "2",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "CECYTEJ PLANTEL TONALA EL PANORAMICO (EXTENSION TOLOLOTLAN)",
      clave: "14XTC0003V",
      turno: "MATUTINO",
      entidad: "JALISCO",
      municipio: "AMECA",
      localidad: "PUENTE GRANDE",
      tipoedu: "MEDIA SUPERIOR",
      nivel: "BACHILLERATO",
      subNivel: "TECNOLÓGICO",
      control: "PÚBLICO",
      subControl: "ESTATAL",
      idTurno: "1",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    },
    {
      nombre: "INSTITUTO DE ESPECIALIZACION EN COMPUTACION Y COMERCIO DE JALISCO",
      clave: "14PBH0380U",
      turno: "DISCONTINUO",
      entidad: "JALISCO",
      municipio: "ARANDAS",
      localidad: "TONALÁ",
      tipoedu: "MEDIA SUPERIOR",
      nivel: "BACHILLERATO",
      subNivel: "BACHILLERATO GENERAL",
      control: "PRIVADO",
      subControl: "PRIVADO",
      idTurno: "4",
      estatus: 0,
      abrev: "JAL",
      fechaActualizacion: "24/02/2026"
    }
  ]
};